### ISSUE TITLE
Bump stop time even when start time occurs even if there's no activity

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#12864]
It doesn't appear https://github.com/coder/coder/commit/290180b1047ef1304b4cc15570dcbad32a073e40 addressed the issue completely for us.

I have this example occur:

- user has workspace with auto-start at 9:00am, 12 hour auto-stop.
- coder stops workspace at 9:00pm.
- user starts workspace at 9:45pm.
- coder does not action on workspace auto-start at 9:00am.
- coder stops workspace at 9:45am.
- user returns mid-day to find workspace he thought would be running wasn't.

Is it possible to make the auto-stop interval bump at auto-start time regardless of activity? I'd prefer consistency in user expectations over wasting some dollars in the cases where on-call engineers need to start their workspaces out of their usual window.

**Comment by stirby** [comment]
@sreya we fixed this previously, could be a regression.

Original issue: https://github.com/coder/coder/issues/2028
Fixing commit: https://github.com/coder/coder/commit/290180b1047ef1304b4cc15570dcbad32a073e40

**Comment by Emyrk** [comment]
@stirby we did not fix this issue because the current behavior requires activity. The issue posted is to extend the auto-stop in the case **there is no activity**.

Said differently, the current solution to this problem is implemented in `activityBumpWorkspace`. If no activity happens, the extension is not applied. I will take a look if we can put this elsewhere, or in two places.

**Comment by Emyrk** [comment]
After talking with @johnstcn, I am going to fix this upfront on the deadline calculation.

https://github.com/coder/coder/blob/53f7e9e0a18315e95bb166f28c9d7a1a2729306f/coderd/schedule/autostop.go#L77-L77

So when this situation occurs, the deadline will be 23.75hrs after the initial workspace start.

1. User has workspace with auto-start at 9:00am, 12 hour auto-stop.
2. Coder stops workspace at 9pm
3. user starts workspace at 9:45pm.
  - The initial deadline is calculated to be 9:45am
  - This crosses the autostart deadline, so the deadline is extended to 9pm

I will come up with some docs to document this behavior.
