### ISSUE TITLE
VS Code port forwarding stops working after some time

### ISSUE THREAD

**Issue by jaaydenh** [coder/coder#13726]
Repo Steps (For MacOS)

1. Have a running workspace with an auto-forwarded port setup for to serve a site for frontend development e.g. 8080,3000
2. Leave it for 30+ mins, the computer should go to sleep during this time (may also occur without sleeping but less reliable)
3. When returning to VS Code you will see a dialog about reconnecting in one of the 3 possible varieties shown below
4. When returning to the site hosted at 8080, the site will no longer load
5. In VS Code, manually stop forwarding port 8080
6. In VS Code, manually add port 8080, the site at port 8080 will usually load at this point. Sometimes this does not work and a workspace restart is necessary to resolve the port forwarding.

The expectation is that it is not necessary to re-forward the ports or to restart the workspace.

<img width="546" alt="Screenshot 2024-06-27 at 8 21 36 PM" src="https://github.com/coder/coder/assets/1858163/df79efda-5487-4dd6-81cb-0fbc28102e54">
<img width="271" alt="Screenshot 2024-06-27 at 9 56 35 AM" src="https://github.com/coder/coder/assets/1858163/8e8fc58f-bff3-4a9b-b93e-7545ed86b260">
<img width="536" alt="Screenshot 2024-06-28 at 9 37 18 AM" src="https://github.com/coder/coder/assets/1858163/3ee4bb96-935d-4cc5-95bc-8b66bb600bb5">

**Comment by matifali** [comment]
Possibly related to #13664.

**Comment by sreya** [comment]
Should be fixed by https://github.com/coder/coder/pull/14165 and https://github.com/coder/coder/pull/14234

**Comment by BrunoQuaresma** [comment]
Just for the record, I’m still facing this issue on `v2.18.1`.

**Comment by BrunoQuaresma** [comment]
Insight: As @Emyrk mentioned in a Slack conversation, this might be caused by the frequent redeployments on dev.coder.com. Maybe we could automatically re-establish port forwarding when the service is back up?

**Comment by Mikescops** [comment]
Hello, I'm also facing this issue on `v2.20.0`, it's a bit of nightmare when you run a client / server app in dev mode because anytime you take a break you have to force reload all your VSCode windows.

If anyone has a workaround in the meantime lmk thanks!

**Comment by Aghassi** [comment]
Adding here that this also impacts Cursor. My problem mirrors that of OP as well

**Comment by bjornrobertsson** [comment]
Reports also state seeing this with other IDE's like Cursor.

**Comment by bjornrobertsson** [comment]
Similar issue but not necessarily attributed to port forwarding: (potentially degraded with 2.19/2.20) - the `Reload Window` function can fail when reconnecting to (the) workspace. Using it leaves the window in an infinite spinning/loading state. Requires the end-user to close the VSCode window, open a new window, and issue a "open workspace" command -- after which the workspace shows up immediately.

**Comment by Kira-Pilot** [comment]
@matifali to test this issue out and create a new issue if necessary

**Comment by matifali** [comment]
@Kira-Pilot @bjornrobertsson I have extracted the REload Window not working to a separate issue: https://github.com/coder/vscode-coder/issues/473
