### ISSUE TITLE
Organization ID is not available

### ISSUE THREAD

**Issue by emouawad** [coder/coder#13906]
On the home page, before login:

Unexpected Application Error!
Organization ID is not available.

Github authentication enabled.

![Screenshot 2024-07-16 190830](https://github.com/user-attachments/assets/3ba7bc60-740a-4290-b0a5-7eb86c5ab89d)

Version:
ghcr.io/coder/coder:v2.13.0

Used env variables:

```yaml
- CODER_PG_CONNECTION_URL=
- CODER_ACCESS_URL=
- CODER_WILDCARD_ACCESS_URL=

- CODER_EXTERNAL_AUTH_0_ID=
- CODER_EXTERNAL_AUTH_0_TYPE=github
- CODER_EXTERNAL_AUTH_0_CLIENT_ID=
- CODER_EXTERNAL_AUTH_0_CLIENT_SECRET=

- CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS=true
- CODER_OAUTH2_GITHUB_ALLOWED_ORGS=
- CODER_OAUTH2_GITHUB_CLIENT_ID=
- CODER_OAUTH2_GITHUB_CLIENT_SECRET=
```

What is Organization ID: a github or a coder organization?
From the docs, tried to find if this is a config i can set in coder, nothing!

Weirdly enough:
I run this in kubernetes: 
- port-forwarding (no issues)
- ingress (Issue persists)
- istio (no issues)

which led me to think: is this a headers issue?

**Comment by kylecarbs** [comment]
@Emyrk thoughts?

**Comment by Emyrk** [comment]
I think this is a UI bug. @aslilac? 

I will take a look too.

**Comment by Emyrk** [comment]
https://github.com/coder/coder/blob/stevenmasley%2Fpremium_license/site/src/contexts/auth/RequireAuth.tsx#L91-L93


I wonder if there is a caching issue on the FE code. The value comes from here: https://github.com/coder/coder/blob/e8c131502e7910e16134c65e224fcca1107a6969/site/site.go#L376-L376

@emouawad if you force refresh your page to clear any page caching, does the issue persist? And if so, what is the value of the `<meta property="user" content="..." />` in the `<head>` section of the html?

Curious if the `organization_ids` is empty.

Regardless, I'll throw up a PR to make sure that slice is never `nil`, and always `[]` in the empty list case.

**Comment by aslilac** [comment]
> Curious if the `organization_ids` is empty.

`Boolean([]) === true`, so `organization_ids` being present but empty would not fail this check. It would have to `undefined` or `null` or some other value that would convert to `false`.

**Comment by emouawad** [comment]
> https://github.com/coder/coder/blob/stevenmasley%2Fpremium_license/site/src/contexts/auth/RequireAuth.tsx#L91-L93
> 
> I wonder if there is a caching issue on the FE code. The value comes from here:
> 
> https://github.com/coder/coder/blob/e8c131502e7910e16134c65e224fcca1107a6969/site/site.go#L376-L376
> 
> @emouawad if you force refresh your page to clear any page caching, does the issue persist? And if so, what is the value of the `<meta property="user" content="..." />` in the `<head>` section of the html?
> 
> Curious if the `organization_ids` is empty.

Incognito mode.

Mode could that headers related? i wonder why it has different outcome depends which ingress i choose.

![image](https://github.com/user-attachments/assets/45b37039-5b87-41b7-b221-69ffabc8a5ba)

**Comment by Emyrk** [comment]
@emouawad huh, so you are not authenticated and you are getting that error. Do you have a network request that ends in `/me` that is returning something? Clearing your cookies might help if there is some strange authentication state.

> newer versions are handling the error better though.

What is "better"?

----

@aslilac has made a PR that drops the possibility of that error from occurring, when that patch makes it's way to live.

**Comment by Emyrk** [comment]
@emouawad appreciate all the data. The new PR just removes that code (was dead code anyway), so it should be fixed when it goes live.

Nothing seems obvious from what you sent, I was curious if there was some strange auth state with the cookies going on, but that does not seem to be the case.

**Comment by emouawad** [comment]
Please reopen this issue.
Latest release did not fix it - it's now generating a new error.

Unexpected Application Error!
Cannot read properties of undefined (reading '0')

![image](https://github.com/user-attachments/assets/d01ac2e4-4ff6-4f61-afd3-4b0240fdd49c)

**Comment by Emyrk** [comment]
@emouawad this PR was merged yesterday that deleted that line that errored. The first PR ripped out the original error, and after looking further this was the follow up to rip out some other org context code.

https://github.com/coder/coder/pull/13940

**Comment by aslilac** [comment]
Hmm. @Emyrk we could replace this line with `"00000000-0000-0000-0000-000000000000"`, but that still doesn't get to the root of this issue. It's bizarre that this property is ending up `undefined` somehow.

**Comment by Emyrk** [comment]
@aslilac the line was changed to `0000`:: https://github.com/coder/coder/blob/main/site/src/modules/dashboard/DashboardProvider.tsx#L45

**Comment by aslilac** [comment]
yes, but we did that change after the release, so the 2.13 branch still looks like this: https://github.com/coder/coder/blob/release/2.13/site/src/modules/dashboard/DashboardProvider.tsx#L47

**Comment by matifali** [comment]
@emouawad these changes should be available in next mainline release (7th of August) you can test them now using `ghcr.io/coder/coder-preview` images.

**Comment by emouawad** [comment]
ghcr.io/coder/coder-preview:main-2.13.1-devel-03c5d4223

Unexpected Application Error!
r.includes is not a function

![image](https://github.com/user-attachments/assets/25cbe28f-c19b-440a-a402-a22aa4a051bf)

**Comment by Parkreiner** [comment]
I'm digging around a little bit, and I'm wondering if there might be an issue with what we're sending from the server. As in, we're sending a valid JSON value, and it's fully defined – but it happens to be of a type that the frontend isn't expecting

Tomorrow I'm going to do some more digging.

## More context

The minified `r` variable refers to the list of Coder experiments that a deployment has enabled. It's supposed to be an array of strings, with the presence of a string indicating that an experiment is enabled

We have checks in place to ensure that the UI will be stuck in a loading state if the value is ever undefined (especially during the initial loading). The UI is getting past the loading state no problem, though, and I don't see a way for an undefined value to ever slip through. But if we're accidentally sending an incorrect type back, that would be able to bypass the checks while still causing the `.includes` method call to be invalid. That seems like the most likely candidate to me, and TypeScript might not be able to catch this

**Comment by emouawad** [comment]
![image](https://github.com/user-attachments/assets/64f6803b-bffb-46e0-abdb-31a15e8cc7b6)

/v2/experiments and /v2/appearance is returning 401

/v2/entitelements is returning

```json
{
    "features": {
        "access_control": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "advanced_template_scheduling": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "appearance": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "audit_log": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "browser_only": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "control_shared_ports": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "custom_roles": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "external_provisioner_daemons": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "external_token_encryption": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "high_availability": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "multiple_external_auth": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "multiple_organizations": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "scim": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "template_rbac": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "user_limit": {
            "entitlement": "not_entitled",
            "enabled": false,
            "actual": 1
        },
        "user_role_management": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "workspace_batch_actions": {
            "entitlement": "not_entitled",
            "enabled": false
        },
        "workspace_proxy": {
            "entitlement": "not_entitled",
            "enabled": false
        }
    },
    "warnings": [],
    "errors": [],
    "has_license": false,
    "trial": false,
    "require_telemetry": false,
    "refreshed_at": "2024-07-24T04:42:38.327141842Z"
}
```

**Comment by aslilac** [comment]
@emouawad are you running this deployment behind a proxy or anything? I know the `code` field shows a 401, but can you verify that the actual status code of the HTTP request is indeed a 401?

**Comment by emouawad** [comment]
I am running this behind ingress-nginx with no authentication in GKE.
Not sure i got the question right: "code field" ?

All the network requests return 200 success.

![image](https://github.com/user-attachments/assets/1e014d64-9290-43de-b751-b74df7b9e518)

**Comment by aslilac** [comment]
ok, we'll this is definitely the problem

in the debugger screenshot you shared above, that `r` value means that `/experiments` _should_ have replied with a 401 HTTP status, but instead it's coming through as a 200, which means the app is assuming that it's the correct type for a successful response (ie. should have an `experiments` field).

can you try `curl -v https://yourcodedeployment/api/v2/experiments` _without_ nginx in the middle and see what the HTTP status is that way? I feel like nginx isn't carrying the status correctly here.

**Comment by emouawad** [comment]
Issue solved now by removing the ingress-nginx default-backend that redirected 401 to a custom web page. (Not newly introduced) - There must have been a change on coder that affected this - previously was working fine with the default redirect in place.

Thanks for helping! Closing.
