### ISSUE TITLE
site: missing icon for filebrowser

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#15365]
# Problem

Our [filebrowser module](https://github.com/coder/modules/blob/f5ab7995d145971d25766ba826901b7eac4c5227/filebrowser/main.tf#L89) references `/icon/filebrowser.svg` but this currently does not exist in our codebase, resulting in a messy-looking filebrowser icon:

![Image](https://github.com/user-attachments/assets/888c7f41-b4a0-44ea-babc-39850e7e3207)

**Comment by johnstcn** [comment]
Fixed by https://github.com/coder/coder/commit/dc29b812861b3db92026e0779d74eea7d8018e2d

![Image](https://github.com/user-attachments/assets/103caf5e-fec2-45b6-ac30-2e43f036e580)

**Comment by gjrtimmer** [comment]
BTW, looks like this is still going on in version 2.16.1, I still have this issue.

**Comment by johnstcn** [comment]
@gjrtimmer thanks for the heads-up; this one never got cherry-picked to 2.16. It should be fixed in the next patch release for that version.
