### ISSUE TITLE
Workspace schedule bumpers are broken

### ISSUE THREAD

**Issue by ammario** [coder/coder#2764]
## Problem
Bumpers in the workspace schedule are broken

## Steps to reproduce
1. Press a + or - button and observe error

<img width="562" alt="Screen Shot 2022-06-30 at 2 41 58 PM" src="https://user-images.githubusercontent.com/7416144/176763551-3e5ff8bc-7ee7-4391-aea9-242b01c850f1.png">

<img width="755" alt="Screen Shot 2022-06-30 at 2 42 41 PM" src="https://user-images.githubusercontent.com/7416144/176763684-8db71771-bd9b-4e1a-87b5-16c643ef26f2.png">

## Definition of Done
A user should be able to modify the shutdown using the bumpers + or -
---

Perhaps it is following the template policy correctly, but the error makes it appear broken.

**Comment by misskniss** [comment]
The current value set on the lease could be great than that on the template - we may not be checking the template? (@johnstcn ). Potential: Grey out a bumper if it is not possible any more?

**Comment by misskniss** [comment]
related: #2942

**Comment by presleyp** [comment]
Validation on the FE (disabling the buttons) is the best solution here but I will surface the backend error in #3097 as well (it'll only come through if FE validation fails for some reason).

**Comment by ammario** [comment]
This was fixed at some point.

**Comment by johnstcn** [comment]
@ammario there's still an issue with the ➕  bumper and workspace templates with max TTL < 24h. https://github.com/coder/coder/pull/3532 should fix this when it's merged.
