### ISSUE TITLE
Visual artifacts when using Emacs in Terminal

### ISSUE THREAD

**Issue by weaversa** [coder/coder#3371]
When using Emacs in Coder's Terminal (either through the web interface or, surprisingly, coder's ssh api through my local terminal), visual artifacts appear on the screen (see attached screen shot). This is momentarily fixed by refreshing the screen (ctrl+l). This behavior is most notable when using split screen (ctrl+x 3).

This behavior does not occur when running the container locally. I've tried w/ a few different containers and Coder exhibited these visual artifacts for them all.

One last thing I tried - No artifacts appear if I launch VS Code from Coder's web interface and then run Emacs inside VS Code's Terminal. This is a pretty cludgy workaround, but may point to something in Coder's Terminal interface interfering w/ Emacs's ability to control the display.

Any assistance is appreciated, including proper guidance on how to use Coder w/ Emacs for development. Thank you!

![image](https://user-images.githubusercontent.com/7407930/182671551-443405f1-d8f6-4521-8204-c5fead580912.png)

**Comment by kylecarbs** [comment]
We must have an issue with our TTY sizing, that'd be the only reason I can imagine this happening.

The width is maybe off-by-one 🤔

**Comment by ammario** [comment]
@weaversa we have a guide on Emacs [here](https://coder.com/docs/coder-oss/latest/ides/configuring-emacs-tramp).

**Comment by weaversa** [comment]
> @weaversa we have a guide on Emacs [here](https://coder.com/docs/coder-oss/latest/ides/configuring-emacs-tramp).

That guide is awesome! Thank you @ammario for sending it along. I will give it a go. Thanks to @kylecarbs as well -- it will be nice to have emacs (and perhaps other terminal based tools) work better when run inside the container via your Terminal interface.

**Comment by code-asher** [comment]
Does this reproduce for you with `emacs -q`?  I tried reproducing but so far no artifacts so I am wondering if there might be some config needed to trigger it.

**Comment by code-asher** [comment]
I do get some odd behavior if I refresh the page (which will trigger a reconnect) but I am not sure if it is the same problem.  The string `0;276;0c11;rgb:1f1f/1f1f/1f1f` gets printed and then when I backspace a line it will delete the border as well.  Sometimes I get a scrollbar as well when I should not and can scroll up to see previous renders of the Emacs window.

![chars](https://user-images.githubusercontent.com/45609798/183484740-7f53f7f2-0841-434e-9e0c-b7f862049724.png)

**Comment by weaversa** [comment]
@code-asher thanks for looking into this! I tried your `-q` suggestion but still get the same behavior. When I refreshed the browser I get a red colored `0;276;0csd` to appear at the cursor - similar, but not the same as yours.

To provide some structure to anyone trying to reproduce this, here are some (hopefully) repeatable steps:

   - Create a new workspace using codercom/enterprise-base:centos
   - Click on the Terminal under "Browser applications"
   - `$ sudo yum install emacs`
   - `$ emacs -q`
   - make a few lines of random text
   - ctrl+x 3 (artifacts should appear)

**Comment by weaversa** [comment]
Oddly enough, the artifacts don't appear when trying the same (split screen) in `vim`.

**Comment by code-asher** [comment]
> Oddly enough, the artifacts don't appear when trying the same (split screen) in vim.

I was just trying the same thing. :laughing:  The only weird things I saw with Vim were that my split size or screen position would change when I refresh (and the same scrollbar issue).  But no disappearing borders.  I could see it being related to sizing like @kylecarbs mentioned.

I was testing on Emacs 26 so I tried Emacs 28 and while I still sometimes get that random string inserted on refresh I do not see any disappearing borders anymore.

I have seen that string appear elsewhere (like when running Webpack) so it might be a separate issue though.

**Comment by weaversa** [comment]
I am still seeing the artifacts with Emacs 28.1.

**Comment by mafredri** [comment]
I'm seeing artifacts in NeoVIM tooo. No settings are needed but `:set number` makes repro easier (adding newlines at the top of a file causes artifacts easily). What seems to help is `TERM= nvim ...` (e.g. `unset TERM`). Typically I have `TERM=xterm-256color` but artifacts are present even with `TERM=xterm` or `TERM=screen`. The reason `unset TERM` works is likely that it disables most fancy features, like colors.

This is using `ssh coder.work`, the problem seems even worse when using `coder ssh work` until I resize my terminal the first time, after that it behaves the same as `ssh coder.work`.

I tried playing around with terminfo a bit by updating instructions for `xterm-256color` (`infocmp xterm-256color > xterm.ti; vim xterm.ti; tic xterm.ti`) to match what `nvim -V` sees on another system (where there are no artifacts). But this was of no use.

Removing the translation of `\n` to `\r\n` in `gliderlabs/ssh` seems to help a bit: https://github.com/gliderlabs/ssh/blob/777ab346580bfadbd48a488111be4569f91aff46/session.go#L133-L136

But it doesn't seem to be a complete solution, might also cause other problems. Essentially this looks like our terminal is not in the right mode and as such, not all terminal codes are conveyed properly.

For reference to anyone looking deeper into this, here are some changes that they over at Tailscale ended up doing to the `gliderlabs/ssh` package: https://github.com/gliderlabs/ssh/compare/master...tailscale:ssh:master (although currently it lives under https://github.com/tailscale/tailscale/tree/main/tempfork/gliderlabs/ssh).

**Comment by ammario** [comment]
Likewise: seeing minor artifacts in nvim.

**Comment by kylecarbs** [comment]
@mafredri what do you think about trying to use their fork instead?

**Comment by mafredri** [comment]
@kylecarbs Perhaps we should cherry-pick relevant commits into our own fork? They have some other changes related to how SSH auth works in tailscale, which we don't really need.

I can create a minimal PR that uses their fork though and the necessary changes to utilize it. But I believe there is more work to be done in this category (not related to fixing `gliderlabs/ssh`).

For instance, here are some differences in `stty -a` output when comparing a regular openssh server vs. going through coder (`ssh coder.ws`):

```diff
--- stty-openssh.txt	2022-08-11 12:36:27.000000000 +0300
+++ stty-ssh-coder.txt	2022-08-11 12:36:54.000000000 +0300
@@ -1,6 +1,6 @@
 speed 38400 baud; rows 63; columns 238; line = 0;
-intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = M-^?; eol2 = M-^?; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
+intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
 -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
--ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel iutf8
+-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
 opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
 isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

There are additional differences when comparing `ssh coder` and `coder ssh`:

```diff
--- stty-ssh-coder.txt	2022-08-11 12:36:54.000000000 +0300
+++ stty-coder-ssh.txt	2022-08-11 12:37:07.000000000 +0300
@@ -1,5 +1,6 @@
-speed 38400 baud; rows 63; columns 238; line = 0;
-intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
+speed 38400 baud; rows 128; columns 128; line = 0;
+intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S;
+susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
 -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
 -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
 opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
```

We probably want these to match OpenSSH as closely as possible, but I don't know if matching the settings will solve everything.

**Comment by mafredri** [comment]
I started out with using `tailscale.com/tempfork/gliderlabs/ssh`, however, due to their other forks I decided to go the `cherry-pick` route:

```
agent/agent.go:297:29: cannot use randomSigner (variable of type "golang.org/x/crypto/ssh".Signer) as type "tailscale.com/tempfork/gliderlabs/ssh".Signer in array or slice literal:
	"golang.org/x/crypto/ssh".Signer does not implement "tailscale.com/tempfork/gliderlabs/ssh".Signer (wrong type for PublicKey method)
		have PublicKey() "golang.org/x/crypto/ssh".PublicKey
		want PublicKey() "github.com/tailscale/golang-x-crypto/ssh".PublicKey
agent/agent.go:319:25: cannot use func(ctx ssh.Context) *gossh.ServerConfig {…} (value of type func(ctx "tailscale.com/tempfork/gliderlabs/ssh".Context) *"golang.org/x/crypto/ssh".ServerConfig) as type "tailscale.com/tempfork/gliderlabs/ssh".ServerConfigCallback in struct literal
```

With that in mind, I wanted to see if this will fix our issues, so I borrowed some additional code from `tailscale.com/ssh/tailssh` to set termios as well.

This is a pretty quick-and-dirty change, we probably want to refactor, ensure it works correctly with reconnecting PTY, as well as other platforms: https://github.com/coder/coder/pull/3473

**Comment by mafredri** [comment]
@weaversa would you be open to trying out the https://github.com/coder/coder/tree/mafredri/fix-terminal-modes branch to see if it fixes the Emacs artifacts? This would help us see if it's the right approach to fix this issue.

The way to test this out is to build the branch manually and use the built binary both for `coder server` and client commands (e.g. `coder ssh`):

```
git clone --depth=1 -b mafredri/fix-terminal-modes https://github.com/coder/coder.git
cd coder
make build
```

(You can use [dogfood/Dockerfile](https://github.com/coder/coder/blob/e7490701931a68e85c3f61fb6ff7893f214f025d/dogfood/Dockerfile) for building, if you want to avoid installing all the dependencies.)

Then you can use one of the binaries produced in `dist`, e.g. `dist/coder_0.8.5-devel+e2369d5f_linux_amd64`. (You'll also need to restart or recreate workspaces in case they are running between server restart.)

```shell
# Start server.
./coder_0.8.5-devel+e2369d5f_linux_amd64 server

# On client machine
./coder_0.8.5-devel+e2369d5f_linux_amd64 stop my-workspace
./coder_0.8.5-devel+e2369d5f_linux_amd64 start my-workspace
./coder_0.8.5-devel+e2369d5f_linux_amd64 config-ssh --use-previous-options --yes

# SSH in
./coder_0.8.5-devel+e2369d5f_linux_amd64 ssh my-workspace
# Or (assuming config-ssh step above)
ssh coder.my-worksace 
```

For me the branch fixes (NeoVIM) usage across all terminals, `ssh`, `coder ssh` and web terminal.

**Comment by weaversa** [comment]
Thank you @mafredri. I've currently only got a mac and spotty internet. I'll have more resources next week, will give it a go, and let you know the results. Also, I understand if you prefer not to wait for me.

**Comment by weaversa** [comment]
@mafredri It does not seem possible for me to build coder. I've tried `make build` in an Ubuntu 20 ec2 instance and using your dogfooding Dockerfile and both fail at various points.

Since your branch fixes your problems, I suggest you incorporate it and I will test things out again on my side after the next update lands. If I have still experience issues I will report them here.

**Comment by mafredri** [comment]
This issue should now be fixed (by #3473). I’ve tested it on both Linux and Windows and everything seemed to work fine. Although on Windows we make no attempts to set terminal modes because there’s no termios support for it.

It might be possible to implement though, a thing like [termiWin](https://github.com/veeso/termiWin) exists (written in C).

@weaversa feel free to try this out as part of the next release. Remember to update server and client and restart workspaces so that everything is up-to-date.

**Comment by weaversa** [comment]
@mafredri The version of Coder I have access to is `Coder v1.35.1 650fd2647`, which I think you call `Coder v1`. This issue still persists (for me) in that instantiation of Coder. Perhaps I was asking for a fix in the wrong place?

**Comment by weaversa** [comment]
@kylecarbs Do you know whether or not this fix can be applied to your `Coder v1` tool?

**Comment by code-asher** [comment]
@weaversa Sorry for the radio silence.

I was just looking into a separate artifact-causing issue on v1 so I can take a look at porting these fixes over as well.

**Comment by weaversa** [comment]
> @weaversa Sorry for the radio silence.
> 
> I was just looking into a separate artifact-causing issue on v1 so I can take a look at porting these fixes over as well.

Thank you @code-asher! I've been using vimacs to get around the issue thus far...I don't know that I have the will to fully learn vi...just for Coder  :-P

**Comment by code-asher** [comment]
Just a heads up that the fixes will be released in 1.38.

**Comment by weaversa** [comment]
> Just a heads up that the fixes will be released in 1.38.

Thank you!!!

**Comment by weaversa** [comment]
I just tried 1.38.2 and emacs works w/ no artifacts! Thank you so much!!!
