### ISSUE TITLE
bug: version is unknown on 0.9.1

### ISSUE THREAD

**Issue by matifali** [coder/coder#4222]
![Screenshot from 2022-09-27 10-57-48](https://user-images.githubusercontent.com/10648092/192471108-9b4d9129-1a8a-4ba4-a96e-1b0019ea5a9b.png)

**Comment by matifali** [comment]
I am using 2.22.0, and this is only for the workspace that were created from 0.8.15. workspaces created after the 0.9.0 update shows the version correctly.

**Comment by kylecarbs** [comment]
Ahh, gotcha. This should be fixed going forward as well, there was just an unfortunate bug in our provider code!

**Comment by matifali** [comment]
not resolved. still seeing an unknown version on 0.9.1. For a newly created template.

**Comment by kylecarbs** [comment]
Ahh, interesting. Can you consistently reproduce this @matifali? Or is it intermittent?

**Comment by matifali** [comment]
It is intermittent. And happens mostly when we update a running workspace after a new template push.

**Comment by matifali** [comment]
> It is intermittent. And happens mostly when we update a running workspace after a new template push.

This is consistent after updating a workspace
